# Noctalia Theme for Mango
# Generated automatically by Noctalia

shadowscolor = 0x000000ff
rootcolor = 0x0e1415ff
bordercolor = 0x899294ff
dropcolor = 0x81d3de80
splitcolor = 0xb9c6eaff
focuscolor = 0x81d3deff
maximizescreencolor = 0xb1cbcfff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xb9c6eaff
globalcolor = 0x004f56ff
overlaycolor = 0x324b4eff
jump_label_decorate_fg_color = 0xdee4e4ff
jump_label_decorate_bg_color = 0x252b2cff
jump_label_decorate_focus_fg_color = 0x00363bff
jump_label_decorate_focus_bg_color = 0x81d3deff
jump_label_decorate_border_color = 0x899294ff
group_bar_decorate_fg_color = 0xdee4e4ff
group_bar_decorate_bg_color = 0x252b2cff
group_bar_decorate_focus_fg_color = 0x00363bff
group_bar_decorate_focus_bg_color = 0x81d3deff
group_bar_decorate_border_color = 0x899294ff
