$mod = SUPER

monitor = ,preferred,auto,1

input {
    kb_layout = de
    follow_mouse = 1
}

bind = $mod, Return, exec, ghostty
bind = $mod, D, exec, fuzzel
bind = $mod SHIFT, Q, killactive
bind = $mod SHIFT, E, exit
bind = $mod, F, fullscreen
