[package]
name = "nix-settings-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "nix-settings"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.6.1", features = ["derive"] }
nix-settings-core = { path = "../core" }
oneshot = { version = "0.2.1", features = ["std"], default-features = false }
portable-pty = "0.9.0"
ratatui = { version = "0.30.0", features = ["crossterm"], default-features = false }
time = { version = "0.3.47", features = ["formatting", "local-offset", "macros"], default-features = false }
tui-term = { version = "0.3.4", default-features = false }
vt100-ctt = "0.17.1"
